# =============================================================================
# visualize.py
#
# Reads the .raw image files generated by generate_test_image and displays
# them visually so you can see what each test pattern looks like.
#
# HOW TO RUN (in your Ubuntu terminal):
#   python3 visualize.py
#
# WHAT IT DOES:
#   Reads each .raw file as raw bytes, reshapes into a 2D grid,
#   and displays it as a grayscale image using matplotlib
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
import os

# Image dimensions - must match what generate_test_image used
WIDTH  = 64
HEIGHT = 64

# List of all test images we want to display
# Each entry is (filename, title_for_display)
test_images = [
    ("test_rect.raw",       "Rectangle"),
    ("test_horizontal.raw", "Horizontal Edge"),
    ("test_vertical.raw",   "Vertical Edge"),
    ("test_diagonal.raw",   "Diagonal Edge"),
    ("test_circle.raw",     "Circle"),
]

# Create a figure with 5 subplots side by side
# figsize=(20, 4) makes it wide enough to show all 5 comfortably
fig, axes = plt.subplots(1, 5, figsize=(20, 4))
fig.suptitle("Test Images for Canny Edge Detection Pipeline", fontsize=14)

for i, (filename, title) in enumerate(test_images):

    # Check the file exists before trying to read it
    if not os.path.exists(filename):
        print(f"WARNING: {filename} not found - run generate_test first!")
        axes[i].set_title(f"{title}\n(FILE NOT FOUND)")
        axes[i].axis('off')
        continue

    # numpy.fromfile reads the raw bytes from the file into a 1D array
    # dtype=np.uint8 means each byte is treated as an unsigned 8-bit integer
    # (values 0 to 255 - exactly our pixel format)
    pixels = np.fromfile(filename, dtype=np.uint8)

    # reshape(HEIGHT, WIDTH) converts the flat 1D array into a 2D grid
    # so numpy/matplotlib knows the 2D structure of the image
    image_2d = pixels.reshape(HEIGHT, WIDTH)

    # Display the image in grayscale
    # cmap='gray' means 0=black, 255=white
    # vmin=0, vmax=255 ensures consistent brightness scale across all images
    axes[i].imshow(image_2d, cmap='gray', vmin=0, vmax=255)
    axes[i].set_title(title)
    axes[i].axis('off')  # hide the axis numbers for cleaner look

    print(f"Loaded: {filename} ({WIDTH}x{HEIGHT})")

# Save the visualization as a PNG file you can open in Windows
plt.tight_layout()
plt.savefig("test_images_preview.png", dpi=150, bbox_inches='tight')
print("\nSaved visualization as: test_images_preview.png")
print("Open this file in Windows Explorer to view your test images!")

plt.show()