#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include "image_io.h"
#include "gaussian.h"
#include "sobel.h"
#include "magnitude.h"
#include "direction.h"
#include "nms.h"
#include "double_threshold.h"
#include "hysteresis.h"
#include <ctime>

// Generated by scripts/raw_to_header.py -- defines EMBEDDED_IMAGE,
// EMBEDDED_IMAGE_WIDTH, EMBEDDED_IMAGE_HEIGHT, EMBEDDED_IMAGE_LEN.
// This is how the test image gets into the program at all: the bare-metal
// RISC-V toolchain has no working fopen() under QEMU, so there is no
// runtime image loading here -- the pixel data is baked into the binary
// itself as a byte array at compile time.
#include "embedded_image.h"

/*
 * riscv_main.cpp
 * ==============
 * Entry point for the canny_rv_embedded build. Runs the FULL Canny
 * pipeline twice on the same input image -- once using the L1 magnitude
 * approximation (|Gx| + |Gy|) and once using the true L2 magnitude
 * (sqrt(Gx^2 + Gy^2)) -- so the two techniques can be compared directly
 */

// -----------------------------------------------------------------------
// Prints `buffer` as a hex string, wrapped at 32 hex chars (16 bytes) per
// line, bounded by marker lines. scripts/decode_dump.py looks for exactly
// this "=== DUMP_START ... ===" / "=== DUMP_END ===" pattern when it
// reconstructs a real .raw file from QEMU's captured stdout -- so the
// marker text itself must never change, only what's printed between them.
// -----------------------------------------------------------------------
static void dump_image_hex(const char* stage_name, const uint8_t* buffer,
                            int width, int height) {
    printf("=== DUMP_START name=%s width=%d height=%d ===\n",
           stage_name, width, height);
    int total = width * height;
    for (int i = 0; i < total; i++) {
        printf("%02x", buffer[i]);
        if ((i + 1) % 32 == 0) printf("\n");
    }
    if (total % 32 != 0) printf("\n");
    printf("=== DUMP_END ===\n");
}


// -----------------------------------------------------------------------
// Runs one full pass of the Canny pipeline on `src`, using either the L1
// or L2 magnitude function depending on `use_l2`. Prints a cycle-count
// table for this pass, then hex-dumps five intermediate/final buffers
// (named "<prefix>_gaussian", "<prefix>_magnitude", etc.) so both passes'
// results can be told apart once decoded back into .raw files.
// -----------------------------------------------------------------------
static void run_pipeline(const uint8_t* src, int width, int height,
                         bool use_l2, const char* label, const char* prefix) {
    int n = width * height;

    // One buffer per pipeline stage. aligned_alloc(64, ...) matches the
    // alignment convention used elsewhere in this project (useful later
    // for RVV vector loads/stores, even though this entry point itself
    // only runs the scalar pipeline).
    uint8_t*  blurred    = (uint8_t* )aligned_alloc(64, n);
    int16_t*  Gx         = (int16_t* )aligned_alloc(64, n * sizeof(int16_t));
    int16_t*  Gy         = (int16_t* )aligned_alloc(64, n * sizeof(int16_t));
    uint8_t*  mag        = (uint8_t* )aligned_alloc(64, n);
    uint8_t*  dir        = (uint8_t* )aligned_alloc(64, n);
    uint8_t*  nms_out    = (uint8_t* )aligned_alloc(64, n);
    uint8_t*  thresh_out = (uint8_t* )aligned_alloc(64, n);
    uint8_t*  final_out  = (uint8_t* )aligned_alloc(64, n);

    // ---- Stage 1: Gaussian blur -- smooths noise before edge detection ----
      gaussian_blur(src, blurred, width, height); 

    // ---- Stage 2a: Sobel gradients -- horizontal (Gx) and vertical (Gy)
    //      intensity change at every pixel. Identical regardless of which
    //      magnitude technique runs next
      sobel_gradient(blurred, Gx, Gy, width, height);    

    // ---- Stage 2b: Gradient magnitude -- the ONE stage that actually
    //      differs between the two passes. L1 (|Gx| + |Gy|) is cheaper to
    //      compute (no square root) but a coarser approximation; L2
    //      (sqrt(Gx^2 + Gy^2)) is the mathematically "correct" Euclidean
    //      magnitude but costs more. This is exactly the tradeoff this
    //      comparison exists to measure, both in cycles and in the final
    //      edge map.
    if (use_l2) {
        magnitude_l2(Gx, Gy, mag, width, height);       
    } else {
        magnitude_l1(Gx, Gy, mag, width, height);       
    }

    // ---- Stage 2c: Gradient direction -- the angle of steepest intensity
    //      change at each pixel, needed by NMS to know which neighboring
    //      pixels to compare against.
       direction_compute(Gx, Gy, dir, width, height);     

    // ---- Stage 3: Non-Maximum Suppression -- thins wide gradient ridges
    //      down to single-pixel-wide edges by keeping only local maxima
    //      along the gradient direction.
       nms_u8(mag, dir, nms_out, width, height);           


    // ---- Stage 4: Double threshold -- classifies every pixel as a
    //      strong edge, weak edge, or no edge based on the thresholds
    //      above.
     double_threshold(nms_out, thresh_out, width, height, 15 , 30); 

    // ---- Stage 5: Hysteresis -- promotes weak edges to real edges only
    //      if they connect to a strong edge, discarding the rest. This
    //      produces the final binary edge map.
     hysteresis(thresh_out, final_out, width, height);   

    

    // ---- Hex-dump five buffers for this pass, named "<prefix>_<stage>"
    //      (e.g. "l1_gaussian", "l2_final"). scripts/decode_dump.py turns
    //      each of these into a real .raw file with that exact name, so
    //      the L1 and L2 results never overwrite each other on disk.
    char name[64];
    #define DUMP(suffix, buf) \
        snprintf(name, sizeof(name), "%s_%s", prefix, suffix); \
        dump_image_hex(name, buf, width, height);
    DUMP("gaussian",   blurred)
    DUMP("magnitude",  mag)
    DUMP("nms",        nms_out)
    DUMP("threshold",  thresh_out)
    DUMP("final",      final_out)
    #undef DUMP

    free(blurred); free(Gx); free(Gy); free(mag);
    free(dir); free(nms_out); free(thresh_out); free(final_out);
}

int main() {
    const int width  = EMBEDDED_IMAGE_WIDTH;
    const int height = EMBEDDED_IMAGE_HEIGHT;
    const int n      = width * height;

    // ---- Sanity check: catches a stale/mismatched embedded_image.h
    //      immediately with a clear message, instead of silently reading
    //      past the end of the array or processing garbage pixels.
    if ((unsigned)n != EMBEDDED_IMAGE_LEN) {
        printf("ERROR: width*height (%d) != EMBEDDED_IMAGE_LEN (%u)\n", n, EMBEDDED_IMAGE_LEN);
        printf("Regenerate embedded_image.h with matching EMBED_W/EMBED_H.\n");
        return 1;
    }

    printf("Embedded image: %dx%d (%d bytes)\n", width, height, n);

    // ---- "Load" the image by copying the compiled-in array into a
    //      heap buffer -- no fopen() involved anywhere in this program.
    uint8_t* src = (uint8_t*)aligned_alloc(64, n);
    if (!src) { printf("ERROR: aligned_alloc failed\n"); return 1; }
    memcpy(src, EMBEDDED_IMAGE, n);

    dump_image_hex("input", src, width, height);

    // ---- Run the same input through both magnitude techniques back to
    //      back, so the comparison is apples-to-apples: same pixels, same
    //      thresholds logic, only the magnitude stage differs.
    run_pipeline(src, width, height, false, "L1  |Gx| + |Gy|",       "l1");
    run_pipeline(src, width, height, true,  "L2  sqrt(Gx^2 + Gy^2)", "l2");

    free(src);
    return 0;
}
